### PR TITLE
Fix setting position when -x, -y empty

### PR DESCRIPTION
**Pull request by allemangD**
This fixes a couple of the issues I mentioned in https://github.com/noctuid/tdrop/issues/70#issuecomment-875794600

> There is also a strange case with -A; if the window is hidden then the shortcut brings the window to the front and focuses it. Pressing the shortcut a second time does nothing, even though it should hide the window (since it's focused). Pressing the shortcut a third time does hide window.

Modifying `map_and_reset_geometry` to unconditionally call `windowactivate` after `windowmap` seems to fix this issue... I'm uncertain how this might conflict with `-A` or similar options but I don't think it will. If you're mapping the window, you'd always want it focused too, right?

Edit: I have a hunch this may have side-effects regarding https://github.com/noctuid/tdrop/issues/335; the triple-press behavior sounds similar to what's described there.

Edit: I'm also unsure if this may conflict with behavior from map and create hooks. Again, I don't _think_ it will, but I'm not too familiar with them.

> The window appears in the top-left regardless of context.

This is caused by these lines overriding the values `xoff` and `yoff`. Conditionally executing these preserves empty values, so the conditions in `map_and_reset_geometry` are evaluated correctly.

https://github.com/noctuid/tdrop/blob/fad32b6b1c87c5989cafad6af85e789e4f67946c/tdrop#L350-L351

_However_ this does not necessarily make the window "remember" its position; it simply doesn't reset the position every time, deferring placement behavior to the WM. Gnome 3/mutter seems to place the window somewhere vaguely in the top-left; gnome-tweaks lets me enable "center new windows", in which case the window is always centered. I expect a tiling manager would place the window in a tile.

For me, the question now becomes "how do I get Gnome/mutter to remember a window position after an unmap-remap?". As far as I can tell there's not really a way to do this. Using gnome-tweaks to enable "center new windows" is suitable to me for now until I figure out a better solution.

### CODE REVIEW

**Comment by noctuid** [comment]
>  If you're mapping the window, you'd always want it focused too, right?

I think this should be fine. It looks like for some window managers mapping does automatically activate the window and for others it doesn't. With this change you can remove the `else xdotool windowactivate "$wid"` around line 752. Make that change, and I think this should be fine to merge as-is. I'll double check to make sure there aren't issues.

> I have a hunch this may have side-effects regarding #335; the triple-press behavior sounds similar to what's described there.

Yeah I think `-A` was working as a workaround there because it would first map but not activate the window and then the next press would be the same as opening the dropdown on a non-empty desktop. I will fix that issue so `-A`'s current strange behavior isn't needed.

> "how do I get Gnome/mutter to remember a window position after an unmap-remap?"

Maybe it would make sense to add these flags `-X` / `--initial-x`, `-Y` / `--initial-y`, `-H` / `--initial-height`, `-W` / `--initial-width`, and `-R` / `--remember-geometry`.

I don't know if `-R` would always work perfectly. If tdrop unmaps the window, it can record and restore the geometry. It already does this with the `auto_hide` and `auto_show` commands (see the `auto_hide` function around line 870). The problem is I'm not sure what will happen if you have the dropdown mapped on another desktop and bring it to the current desktop with the tdrop hotkey. Does this change the geometry for some window managers? I'm not sure. Handling multi-monitor setups would also require some extra work.

**Comment by allemangD** [comment]
> remote the `else xdotool windowactivate "$wid"`

This is done.

https://github.com/noctuid/tdrop/blob/86fd8f2542e853bbf54df6163878a860ba6bf710/tdrop#L754-L756

**Comment by noctuid** [comment]
Thanks!

**Comment by noctuid** [comment]
@allemangD I had to move the windowactivate to a separate command afterwards to prevent an issue where the old desktop the dropdown was on would be focused on bspwm. Let me know if you have any issues after this change. If you're interested in the `--remember` flag with the caveats I described, I can look into implementing it when I get a chance.

**Pull request merged**
