### PR TITLE
Fix behaviour for of tdrop for i3 wm when the dropdown window is in other workspace

### PR DESCRIPTION
**Pull request by alekcacko**
This analogous adresses #21 but for i3wm instead of mate/marco

### CODE REVIEW

**Comment by noctuid** [comment]
I'd prefer a generic solution if possible. Does `xdotool set_desktop_for_window` work on i3? If it does, please amend the commit to just change that one line to `[[ $visibility =~ ^(IsUnMapped|IsUnViewable)$ ]]...`.

**Comment by alekcacko** [comment]
No, `xdotool set_desktop_for_window`. I just came up with this dirty solution. If you have a better solution, please implement it. Thank you.

**Comment by noctuid** [comment]
I just tested this with i3, and it works fine for me. I've pushed the changes; could you try it now?

**Comment by alekcacko** [comment]
Actually, yes it is working, I may oversaw things. Thank you.

**Pull request closed without merging**
